---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local
  # vars:
  #      api_key:

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!

  - name: install collection
    command: ansible-galaxy collection install ibm.cloudcollection -f
    register: install_logs
  
  - name: Print collection install logs
    debug:
      msg: "Resource Group : {{ install_logs }}"

  - name: Print API KEY
    debug:
      msg: "apikey : {{ api_key }}"
  
  - name: fetch a resource group
    ibm.cloudcollection.ibm_resource_group_info:
      name: "Default"
      ibmcloud_api_key: "{{ api_key }}"
    register: resource_group_output
    #when: install_logs.failed == False

  # - name: Save existing resource group info as fact
  #   set_fact:
  #     cacheable: True
  #     resource_group: "{{ resource_group_output.resource }}"
  #   when: resource_group_output.resource.id is defined

  - name: Print Resource group info 
    debug:
      msg: "Resource Group : {{ resource_group_output }}"
    



