---
# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
  - name: install collection
    command: ansible-galaxy collection install ibm.cloudcollection 
